name: Valdate static MkDocs pages
on:
  pull_request:
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  validate-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build MkDocs pages
        uses: docker://squidfunk/mkdocs-material:7.1.0
        timeout-minutes: 1
        with:
          args: >-
            build
            --verbose
            --strict

      - id: format-github-repo
        run: echo "::set-output name=repo-name::${GITHUB_REPOSITORY#*\/}"

      - name: Test links
        timeout-minutes: 10
        uses: docker://klakegg/html-proofer:3.16.0
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          args: >-
            --allow-hash-href
            --check-html
            --http-status-ignore 302
            --file-ignore ./site/404.html
            --url-ignore "https://fonts.gstatic.com,/github.com\/htcondor\/${{ steps.format-github-repo.outputs.repo-name }}\/edit/,/htcondor-ce.org\/${{ steps.format-github-repo.outputs.repo-name }}/"
            ./site
